# Generated by Django 2.2.10 on 2020-04-15 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190630_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='ratting',
            field=models.FloatField(default=5),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('C', 'Cat'), ('D', 'Dog'), ('P', 'Parrot')], max_length=2),
        ),
    ]
