# Generated by Django 2.2.10 on 2020-04-15 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200415_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='ratting',
            field=models.FloatField(default=0),
        ),
    ]
